// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1745831751);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1745831751);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1745831751);
user_pref("app.update.lastUpdateTime.region-update-timer", 1745313842);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1745831751);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1745313866);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1745831751);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{8f24f01c-be7e-4d12-b2cb-a6dc224463ea}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 148);
user_pref("browser.newtabpage.activity-stream.impressionId", "{68890a1f-025f-43cb-bf54-d8113ff98c51}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1745831721);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1745313812015");
user_pref("distribution.iniFile.exists.appversion", "128.8.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECLEsPUq5t9hcBAjBRXCfcCjK1Q==");
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20250224130137");
user_pref("extensions.lastAppVersion", "128.8.0");
user_pref("extensions.lastPlatformVersion", "128.8.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"33800a53-3e63-4033-8267-b2e2eda37503\",\"pictureinpicture@mozilla.org\":\"1702c3b9-93d6-42ee-82ae-2b7b0e3c0ae3\",\"screenshots@mozilla.org\":\"afb5c6fa-8b35-43bf-8f23-78eedc1510c1\",\"webcompat-reporter@mozilla.org\":\"b7a53d49-3ab5-4f46-bb02-e1b775a5a613\",\"webcompat@mozilla.org\":\"68f87be1-4896-4889-8a22-02fbedadd151\",\"default-theme@mozilla.org\":\"e7dc5b07-1f81-4ea5-9d1c-50fea8c637ae\",\"addons-search-detection@mozilla.com\":\"e58692b3-3d73-45ee-b4d5-c745004a142e\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1745831782);
user_pref("media.gmp-manager.buildID", "20250224130137");
user_pref("media.gmp-manager.lastCheck", 1745831741);
user_pref("media.gmp-manager.lastEmptyCheck", 1745831741);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1745314068);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1745831782419");
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs2", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "7a210476-0857-4aca-9130-1c8b3476e5e8");
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECCU6pf7fMQ5VBAi/3AIcIdgdbA==");
user_pref("storage.vacuum.last.content-prefs.sqlite", 1745593618);
user_pref("storage.vacuum.last.index", 2);
user_pref("storage.vacuum.last.places.sqlite", 1745314068);
user_pref("toolkit.startup.last_success", 1745831715);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20250224130137");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
